import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'error':                       '#b02500',
        'on-background':               '#2d2f2f',
        'on-tertiary-fixed':           '#1d0054',
        'primary-dim':                 '#435600',
        'surface-bright':              '#f6f6f6',
        'surface-container-lowest':    '#ffffff',
        'error-dim':                   '#b92902',
        'inverse-primary':             '#cafd00',
        'on-tertiary-container':       '#3a0093',
        'inverse-on-surface':          '#9c9d9d',
        'outline-variant':             '#acadad',
        'inverse-surface':             '#0c0f0f',
        'surface-tint':                '#4e6300',
        'secondary-fixed':             '#ffbdf3',
        'tertiary-dim':                '#5d00e3',
        'tertiary-fixed':              '#bba2ff',
        'on-primary-fixed':            '#3a4a00',
        'surface-container-high':      '#e1e3e3',
        'error-container':             '#f95630',
        'surface-container':           '#e7e8e8',
        'on-tertiary-fixed-variant':   '#4400aa',
        'on-secondary-container':      '#820082',
        'surface':                     '#f6f6f6',
        'primary-container':           '#cafd00',
        'on-primary-container':        '#4a5e00',
        'on-primary-fixed-variant':    '#526900',
        'tertiary-fixed-dim':          '#ae91ff',
        'on-surface':                  '#2d2f2f',
        'on-secondary':                '#ffeef8',
        'tertiary':                    '#6a1cf6',
        'secondary-dim':               '#900090',
        'surface-container-highest':   '#dbdddd',
        'secondary-container':         '#ffbdf3',
        'surface-dim':                 '#d2d5d5',
        'on-error':                    '#ffefec',
        'on-secondary-fixed':          '#620061',
        'surface-variant':             '#dbdddd',
        'outline':                     '#757777',
        'secondary':                   '#a400a4',
        'primary-fixed-dim':           '#beee00',
        'on-tertiary':                 '#f7f0ff',
        'secondary-fixed-dim':         '#ffa6f3',
        'on-primary':                  '#e1ff88',
        'on-error-container':          '#520c00',
        'background':                  '#f6f6f6',
        'on-secondary-fixed-variant':  '#920091',
        'on-surface-variant':          '#5a5c5c',
        'tertiary-container':          '#bba2ff',
        'primary-fixed':               '#cafd00',
        'surface-container-low':       '#f0f1f1',
        'primary':                     '#4e6300',
      },
      fontFamily: {
        'headline': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body':     ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'label':    ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg:      '0px',
        xl:      '0px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
